"use client";

/**
 * Collapsed-by-default panel that asks the server for an AI hypothesis about
 * why the latest run failed or errored. Rendered only on the metric detail
 * page and only when ``latestRun.status`` is ``failed`` or ``error`` —
 * passed/warning runs skip this surface entirely.
 *
 * Three visual states:
 *
 * - **Idle.** Collapsed button; nothing fetched yet. Shows a preloaded
 *   explanation via the ``initial`` prop if the server already has one
 *   (the SSR page fetches it alongside the metric).
 * - **Loading.** User clicked — spinner + copy reminding them this blocks up
 *   to ~30s on an upstream model call.
 * - **Error.** If the server returns 500 "not configured" we show a muted
 *   line instead of a red banner, per the v0.2 UX brief.
 */

import { useState } from "react";
import {
  ExplainError,
  explainRun,
  type RunExplanation,
} from "@/lib/api";

interface WhyDidThisFailProps {
  runId: string;
  /** Raw run status from the server ("failed", "error", ...). */
  status: string;
  /** Pre-fetched explanation if the server already generated one. */
  initial?: RunExplanation | null;
}

type ViewState =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "ok"; data: RunExplanation }
  | { kind: "not_configured" }
  | { kind: "error"; message: string };

function renderRelative(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

export function WhyDidThisFail({
  runId,
  status,
  initial,
}: WhyDidThisFailProps) {
  const normalized = status.toLowerCase();
  if (normalized !== "failed" && normalized !== "error" && normalized !== "errored") {
    // Defensive — the page shouldn't mount us for non-failed runs, but if it
    // does we must render nothing rather than tempt users to burn tokens.
    return null;
  }

  const [view, setView] = useState<ViewState>(
    initial ? { kind: "ok", data: initial } : { kind: "idle" },
  );

  async function runExplain(regenerate: boolean) {
    setView({ kind: "loading" });
    try {
      const data = await explainRun(runId, { regenerate });
      setView({ kind: "ok", data });
    } catch (err) {
      if (err instanceof ExplainError && err.statusCode === 500) {
        setView({ kind: "not_configured" });
        return;
      }
      const message = err instanceof Error ? err.message : String(err);
      setView({ kind: "error", message });
    }
  }

  return (
    <section className="rounded-xl border border-red-200 bg-red-50/40 p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h3 className="text-sm font-semibold uppercase tracking-wide text-red-700">
            Why did this fail?
          </h3>
          <p className="mt-1 text-sm text-neutral-700">
            One-paragraph hypothesis generated by Claude, grounded in the
            failing check&rsquo;s numbers and recent run history.
          </p>
        </div>
        {view.kind === "idle" && (
          <button
            type="button"
            onClick={() => runExplain(false)}
            className="rounded-md bg-red-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2"
          >
            Explain this failure
          </button>
        )}
        {view.kind === "ok" && (
          <button
            type="button"
            onClick={() => runExplain(true)}
            className="rounded-md border border-red-300 bg-white px-3 py-1.5 text-xs font-medium text-red-700 hover:bg-red-100"
          >
            Regenerate
          </button>
        )}
      </div>

      {view.kind === "loading" && (
        <p className="mt-4 text-sm text-neutral-600">
          Thinking&hellip; this usually takes 5&ndash;15 seconds.
        </p>
      )}

      {view.kind === "ok" && (
        <div className="mt-4 space-y-3 text-sm">
          <div>
            <div className="text-xs uppercase tracking-wide text-neutral-500">
              Hypothesis
            </div>
            <p className="mt-1 text-neutral-800">{view.data.hypothesis}</p>
          </div>
          <div>
            <div className="text-xs uppercase tracking-wide text-neutral-500">
              Suggested next step
            </div>
            <p className="mt-1 text-neutral-800">
              {view.data.suggestedAction}
            </p>
          </div>
          <p className="text-[11px] text-neutral-500">
            Generated {renderRelative(view.data.createdAt)} by{" "}
            <code>{view.data.modelId}</code>. AI output — verify before acting.
          </p>
        </div>
      )}

      {view.kind === "not_configured" && (
        <p className="mt-4 text-sm text-neutral-500">
          AI explanations not configured on this instance.
        </p>
      )}

      {view.kind === "error" && (
        <div className="mt-4 rounded-md border border-red-300 bg-white p-3 text-sm text-red-800">
          <p className="font-medium">Could not generate an explanation.</p>
          <p className="mt-1 text-xs font-mono text-red-700">{view.message}</p>
          <button
            type="button"
            onClick={() => runExplain(false)}
            className="mt-2 text-xs font-medium text-red-700 underline"
          >
            Try again
          </button>
        </div>
      )}
    </section>
  );
}
